# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='instruct',
            field=models.CharField(default=1, max_length=500),
        ),
    ]
