# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0002_task_instruct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='instruct',
        ),
    ]
