# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0003_remove_task_instruct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='parent_task',
            new_name='subtask_title',
        ),
    ]
