# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0006_subtask_is_right'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='is_right',
            new_name='is_favorite',
        ),
    ]
