# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0007_auto_20161111_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='instructions',
            field=models.TextField(default='NULL'),
        ),
    ]
