# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0009_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_solution', models.TextField(default='NULL')),
            ],
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsrc.Subtask'),
        ),
        migrations.AddField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsrc.Task'),
        ),
    ]
