# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0010_auto_20161116_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='task',
        ),
    ]
